sudo: required

services:
  - docker

language: python
python:
  - "3.6"

before_script:
  - sudo apt-get -q update && sudo apt-get install pwgen

script:
  - ./test_autoversion.py
  - ./autoversion.py --check
  - env TEST_OPEN_SOURCE=1 ./test_docs.py 07.Administration/02.Production-installation/docs.md
  - if [ -n "$DOCKER_PASSWORD" ]; then docker login -u menderbuildsystem -p "$DOCKER_PASSWORD"; fi
  - if [ -n "$DOCKER_PASSWORD" ]; then env TEST_ENTERPRISE=1 ./test_docs.py 07.Administration/02.Production-installation/docs.md; fi
  - if [ -n "$DOCKER_PASSWORD" ]; then env TEST_ENTERPRISE=1 ./test_docs.py 07.Administration/02.Production-installation/01.Upgrading-from-OS-to-Enterprise/docs.md; fi

after_success:
  # on merge, first deploy to staging, wait 5 minutes, and deploy to production:
  # note that worse possible outcome here is incorrectly formatted markdown appearing
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then ./redeploy.sh master && sleep 300 && ./redeploy.sh production; fi
